--Note: The E's below some of the strings are to enable "\" to be an escape character, e.g. to escape an apostrophe. (This is necessary since we can't use double-quotes in SQL.)

INSERT INTO questions (text, victim_version, rating)
VALUES
(E'What is $name\'s biggest fear?', 'What is your biggest fear?', 'PG'),
('What would $name request for their death row meal?', 'What would you request for your death row meal?', 'PG'),
(E'What is $name\'s sage advice?', 'What is your sage advice?', 'PG'),
('What does $name want to be when they grow up?', 'What do you want to be when you grow up?', 'PG'),
('If $name won $1,000,000, what would they do?', 'If you won $1,000,000, what would you do?', 'PG'),
(E'What is $name\'s guilty pleasure TV show?', 'What is your guilty pleasure TV show?', 'PG'),
('If $name were a fictional character, who would they be?', 'If you were a fictional character, who would you be?', 'PG'),
('How would $name survive the apocalypse?', 'How would you survive the apocalypse?', 'PG'),
('If $name were a potato, how would they be cooked?', 'If you were a potato, how would you be cooked?', 'PG'),
(E'Where is $name\'s favorite place?', 'Where is your favorite place?', 'PG'),
('What would $name do if they were invisible?', 'What would you do if you were invisible?', 'PG'),
(E'What is $name\'s biggest pet peeve?', 'What is your biggest pet peeve?', 'PG'),
(E'What is $name\'s favorite catchphrase?', 'What is your favorite catchphrase?', 'PG'),
('If $name had a superpower, what would it be?', 'If you had a superpower, what would it be?', 'PG'),
('How would $name impress their alien crush?', 'How would you impress your alien crush?', 'PG'),
('What is $name secretly hoarding?', 'What are you secretly hoarding?', 'PG'),
(E'$name\'s favorite Halloween activity: bobbing for ______', 'Your favorite Halloween activity: bobbing for ______', 'PG'),
(E'What is $name\'s favorite quirky fact about themselves?', 'What is your favorite quirky fact about yourself?', 'PG'),
(E'What is $name\'s signature pickup line?', 'What is your signature pickup line?', 'PG'),
(E'What would $name\'s last words be?', 'What would your last words be?', 'PG'),
('What is the name of the hit movie $name would produce?', 'What is the name of the hit movie you would produce?', 'PG'),
('What award is $name most likely to win?', 'What award are you most likely to win?', 'PG'),
('$name just got hired for the traveling circus. What is their main act?', 'You just got hired for the traveling circus. What is your main act?', 'PG'),
('What would $name tell you completely unsolicited?', 'What would you tell people completely unsolicited?', 'PG'),
('If $name were arrested, what would it be for?', 'If you got arrested, what would it be for?', 'PG'),
('What would $name do to get accused of being a witch in Salem?', 'What would you do to get accused of being a witch in Salem?', 'PG'),
(E'$name just called you and asked you to help them bury a body... What\'s the backstory?', E'You just called a friend to help you bury a body... What\'s the backstory?', 'PG'),
(E'What\'s the one achievement $name refuses to remove from their resume?', E'What\'s the one achievement you refuse to remove from your resume?', 'PG'),
('What would $name scream out of the limo on the way to their prom?', 'What would you scream out of the limo on the way to your prom?',
'PG'),
(E'What\'s the first thing $name would eat in their car if it died in the middle of nowhere with no service?', E'What\'s the first thing you would eat in your car if it died in the middle of nowhere with no service?', 'PG'),
('How does $name like their eggs?', 'How do you like your eggs?', 'PG'),
('What would $name bring to a deserted island?', 'What would you bring to a deserted island?', 'PG'),
(E'What is $name\'s guilty pleasure?', 'What is your guilty pleasure?', 'PG'),
(E'What is $name\'s cheat-day meal?', 'What is your cheat-day meal?', 'PG'),
(E'What is $name\'s best quality?', 'What is your best quality?', 'PG'),
(E'What is $name\'s favorite condiment?', 'What is your favorite condiment?', 'PG'),
('If $name could choose any historical figure to be their friend, who would it be?', 'If you could choose any historical figure to be their friend, who would it be?', 'PG')
;
